/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "The Lab": "实验室",
    "Cost: Free": "成本: 免费",
    "Toggle Hover": "切换悬停",
    "Tree Game requires you to enable JavaScript to play. If you don't know what JavaScript is or didn't disable it, try using another web browser.": "升级链 需要您启用 JavaScript 才能玩。如果您不知道 JavaScript 是什么或没有禁用它，请尝试使用其他网络浏览器。",
    "Triple all production.": "三倍所有的生产。",
    "Unlock a new set of rebirth upgrades.\nCost: 1a": "解锁一套新的重生升级。\n成本：1a",
    "Unlock even more rebirth upgrades.\nCost: 1b": "解锁更多重生升级。\n成本：1b",
    "Unlock the Automation tab.": "解锁自动化选项卡。",
    "Unlock the next prestige layer. Nah, just kidding.\nCost: 1.00e100a": "解锁下一个声望层。不，开个玩笑。\n成本：1.00e100a",
    "Unlock you're mom.\nCost: 1.00e100a": "解锁 你是妈妈。\n成本：1.00e100a",
    "Upgrade Tree": "升级树",
    "x boosts y production at a rate of x": "x 以 x 的速度提高 y 的产量",
    "Start producing y.": "开始生产 y。",
    "Start producing z.": "开始生产 z。",
    "Start the game.": "开始游戏。",
    "Cube the core production of x.": "立方体的核心生产x。",
    "Currently ON.": "当前开启。",
    "Developer Options": "开发人员选项",
    "Developer Options reset on refresh.": "开发人员选项在刷新时重置。",
    "Discord Server": "Discord服务器",
    "Dots": "点",
    "Double all production.": "将所有产量翻倍。",
    "Double the production of x.": "x 的产量翻倍。",
    "Double z production.": "双z生产。",
    "Engineering": "工程",
    "Enter The Lab.": "进入实验室。",
    "Export Game": "导出存档",
    "haha this is a placeholder": "哈哈这是一个占位符",
    "Help": "帮助",
    "Help page": "帮助页面",
    "If you see this for over a second, the game probably errored.": "如果您看到这一点超过一秒钟，则游戏可能出错了。",
    "Import Game": "导入存档",
    "Legacy Edition": "传统版",
    "Letters": "字母",
    "Light": "光",
    "Logarithm": "对数",
    "Long": "长",
    "Max All (m": "全部最大（m",
    "Options": "选项",
    "pogger button": "按钮",
    "Production Route": "生产路线",
    "Rebirth Tree": "重生树",
    "Rebirth.": "重生。",
    "Research": "研究",
    "Reset Game": "重置游戏",
    "Respec Rebirth Tree.": "重洗重生树。",
    "Save Game": "保存游戏",
    "Show Upgrade IDs": "显示升级 ID",
    "Square core x production.": "平方核心 x 生产。",
    "Square z production.": "平方 z 生产。",
    "Quadruple all production.": "所有产量翻四倍。",
    "Increase the production of x based on x.": "在 x 的基础上增加 x 的产量。",
    "oi what ya doin": "哦，你在做什么",
    "Another Tree": "另一个树",
    "automaton": "自动化",
    "Automation": "自动化",
    "Automation Route": "自动化路线",
    "Change Notation": "更改符号",
    "Change Tab Bar Prefix": "更改标签前缀",
    "Change Tab Bar Suffix": "更改标签后缀",
    "Change Theme": "更改主题",
    "Clock": "时钟",
    "Content Route": "内容路线",
    "Credits": "鸣谢",
    "Multiply x production by z": "将 x 生产乘以 z",
    "Multiply z production based on z.": "基于 z 乘以 z 生产。",
    "coming in a later update because i cant be bothered to add it now": "稍后更新，因为我现在懒得添加它",
    "Boost y production based on x and z.": "基于 x 和 z 提高 y 产量。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Standard": "标准",
    "Mixed Sci.": "混合科学",
    "Mixed Eng.": "混合工程",
    "Scientific": "科学计数法",
    "Bar": "条",
    "Blind": "盲文",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Increase core production of x by ": "将 x 的核心产量提高 ",
    "Cost: Infinite ": "成本: 无限 ",
    "Raise all production to the power of ": "提高所有生产力 ",
    "Raise x production to the power of ": "提高 x 生产力 ",
    "Raise y production to the power of ": "提高 y 生产力 ",
    "Realize these are all placeholders.\nCost: ": "意识到这些都是占位符。\n成本：",
    "Remove all timewalls from OM.\nCost: ": "从 OM 移除所有时间墙。\n成本：",
    "Leak Yhvr's localhost, getting access to beta beta.\nCost: ": "泄漏 Yhvh 的本地主机，获得对 beta 测试版的访问权限。\n成本：",
    "never gonna give you up, get rique rol't!\nCost: ": "永远不会放弃你，得到 瑞克摇！\成本：",
    "Make everyone realize it's called \"Another Tree\" and not \"abc Tree\".\nCost: ": "让每个人都意识到它被称为“另一棵树”而不是“abc 树”。\n成本：",
    "Make the \"Exponential y\" upgrade more powerful.\nCost: ": "使“指数 y”升级更强大。\n成本：",
    "Migrate from break_infinty to break_eternity.\nCost: ": "从break_infinty迁移到break eternity。\n成本：",
    "Minecraft IRL, your computer turns into a 1-meter cube of solid metal.\nCost: ": "Minecraft IRL，你的电脑变成了一个 1 米长的固体金属立方体。\n成本：",
    "Multiply all production by infinity. Game over, you won.\nCost: ": "将所有生产乘以无穷大。 游戏结束，你赢了。\n成本：",
    "Spend an hour making your terminal look fancy instead of working on the game.\nCost: ": "花一个小时让你的终端看起来很漂亮，而不是在游戏上工作。\n成本：",
    "Realize it's gonna be a while before you can automate a production.\nCost: ": "意识到要实现生产自动化还需要一段时间。\n成本：",
    "help i ran out of ideas.\nCost: ": "帮助我用完了想法。\n成本：",
    "Ghostify IRL.\nCost: ": "幻化 IRL。\n费用：",
    "Gain a small multiplier to RP gain.\nCost: ": "获得 RP 增益的小乘数。\n成本：",
    "Get admin on the Discord server.\nCost: ": "在 Discord 服务器上获取管理员权限。\n成本：",
    "Get around to making all the other options selects instead of buttons.\nCost: ": "转而选择所有其他选项而不是按钮。\n成本：",
    "Boost all production based on how many a's you have bought.\nCost: ": "根据您购买的数量提高所有产量。\n成本：",
    "Boost y production based on x.\nCost: ": "根据 x 提高 y 产量。\n成本：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.]+)(.+)K (.+)$/,
    /^([\d\.]+)(.+)B(.+)$/,
    /^([\d\.]+)(.+)M(.+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) x$/,
    /^([\d\.]+)e([\d\.,]+) y$/,
    /^([\d\.]+)e([\d\.,]+) z$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Better (.+)\nUpgrade to tier (.+)\nCost: (.+)RP\nCurrently: Formula only has (.+)$/, '更好的 $1\n升级到 层 $2\n成本：$3RP\n当前：公式只有 $4'],
    [/^Better (.+)\nUpgrade to tier (.+)\nCost: (.+)RP\nCurrently: (.+)$/, '更好的 $1\n升级到 层 $2\n成本：$3RP\n当前：$4'],
    [/^Core (.+)\nUpgrade to tier (.+)\nCost: (.+)RP\nCurrently: (.+)$/, '核心 $1\n升级到 层 $2\n成本：$3RP\n当前：$4'],
    [/^Dynamic (.+)\nUpgrade to tier (.+)\nCost: (.+)RP\nCurrently: (.+)$/, '动态 $1\n升级到 层 $2\n成本：$3RP\n当前：$4'],
    [/^Cheaper Upgrades\nUpgrade to tier (.+)\nCost: (.+)RP\nCurrently: (.+)$/, '更便宜的升级\n升级到 层 $1\n成本：$2RP\n当前：$3'],
    [/^Production Buff\nUpgrade to tier (.+)\nCost: (.+)RP\nCurrently: (.+)$/, '生产增益\n升级到 层 $1\n成本：$2RP\n当前：$3'],
    [/^RP Buff\nUpgrade to tier (.+)\nCost: (.+)RP\nCurrently: (.+)$/, 'RP增益\n升级到 层 $1\n成本：$2RP\n当前：$3'],
    [/^Static RP\nUpgrade to tier (.+)\nCost: (.+)RP\nCurrently: (.+)$/, '静态RP\n升级到 层 $1\n成本：$2RP\n当前：$3'],
    [/^Get (.+)\/s.\nCost: (.+)$/, '获得 $1\/秒.\n成本: $2'],
    [/^Multiply (.+) production by (.+).$/, '乘以 $1 产量 $2.'],
    [/^Increase core production of (.+) by (.+).$/, '将 $1 的核心产量提高 $2.'],
    [/^Buy (.+) .\nCost: (.+)  Total RP$/, '购买 $1.\n成本: $2 总RP'],
    [/^Buy an (.+) .\nCost: (.+)  Total RP$/, '购买 $1.\n成本: $2 总RP'],
    [/^in (.+)  RP$/, '获得 $1 RP'],
    [/^next in (.+) RP$/, '下一个在 $1RP'],
    [/^Content Expansion\nCost: (.+) Total RP$/, '内容扩展\n成本: $1 总 RP'],
    [/^Buy an a.\nCost: (.+) Total RP$/, '购买 1个 a。\n成本: $1 总 RP'],
    [/^Buy a b.\nCost: (.+) Total RP$/, '购买 1个 b。\n成本: $1 总 RP'],
    [/^Buy a c.\nCost: (.+) Total RP$/, '购买 1个 c。\n成本: $1 总 RP'],
    [/^Boost xyz production by a static (.+).\nCost: (.+)$/, '通过静态 $1 提高 xyz 生产。\n成本：$2'],
    [/^You have (.+) total RP.\n\t\t\tIf you're stuck, check out the$/, '您总共有 $1 RP。\n\t\t\t如果您遇到困难，请查看'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: ([\d\.,]+)$/, '成本：$1'],
    [/^Cost: ([\d\.]+)e([\d\.,]+)$/, '成本：$1e$2'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Cost: (.+)x$/, '成本：$1 x'],
    [/^Cost: (.+)y$/, '成本：$1 y'],
    [/^Cost: (.+)z$/, '成本：$1 z'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);